import torch
import numpy as np
import open3d as o3d
import time

from .inference_utils import align_cam_pts_irls
from .utils.geometry import register_camera_poses_kabsch
from .tsdf_volume import SphericalTSDFVolume  # Import our new GPU Volume

class PanoStreamingEngine:
    def __init__(self, vanilla_engine, window_size=3, overlap=2):
        self.engine = vanilla_engine
        self.window_size = window_size
        self.overlap = overlap
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        
        if self.overlap < 2:
            print("WARNING: Kabsch requires an overlap of >= 2 to guarantee a stable 3D rotation.")
        self.reset()
        
    def reset(self):
        """Clears the temporal memory and initializes a new TSDF Volume."""
        # Initialize a 10m x 10m x 4m room volume centered around the camera
        # At 2cm resolution, this is highly detailed and fits perfectly in VRAM.
        vol_bounds = [[-5.0, 5.0], [-2.0, 2.0], [-5.0, 5.0]]
        self.tsdf = SphericalTSDFVolume(vol_bounds=vol_bounds, voxel_size=0.02, margin=0.15, device=self.device)
        
        self.prev_overlap_raw_pts = []
        self.prev_overlap_global_poses = []
        self.prev_overlap_masks = []
        self.is_first_window = True

    def process_sequence(self, frames, masks):
        """Processes a sequence using Exact Odometry Chaining and TSDF Integration."""
        self.reset()
        num_frames = len(frames)
        
        for i in range(0, num_frames - self.window_size + 1, self.window_size - self.overlap):
            window_frames = frames[i : i + self.window_size]
            window_masks = masks[i : i + self.window_size]
            
            print(f"\n[Streaming Engine] Processing Window {i}...")
            
            t_gpu_start = time.time()
            preds = self.engine(window_frames)
            print(f"  [Profile] GPU Neural Network Inference: {time.time() - t_gpu_start:.4f} sec")
            
            # These are generated by `unproject_equirectangular_to_points` internally
            pts_list = preds["points"] 
            poses = preds["poses"]
            
            if self.is_first_window:
                for j in range(self.window_size):
                    # We integrate the raw depth map tensor directly into the TSDF
                    self.tsdf.integrate(
                        depth_map=preds["depth"][j], 
                        rgb_image=window_frames[j], 
                        mask=window_masks[j], 
                        pose=poses[j]
                    )
                
                self.prev_overlap_raw_pts = pts_list[-self.overlap:]
                self.prev_overlap_global_poses = list(poses[-self.overlap:])
                self.is_first_window = False
                
            else:
                # 1. IRLS Scale Drift Correction (Using points to find alignment)
                t_align_start = time.time()
                scale_diff = align_cam_pts_irls(
                    torch.from_numpy(pts_list[0].copy()), 
                    torch.from_numpy(self.prev_overlap_raw_pts[0].copy()), 
                    torch.from_numpy(window_masks[0].copy())
                )
                print(f"  [Profile] IRLS Alignment took {time.time() - t_align_start:.4f} sec")
                
                # 2. TSDF Integration
                for j in range(self.overlap, self.window_size):
                    self.tsdf.integrate(
                        depth_map=preds["depth"][j], 
                        rgb_image=window_frames[j], 
                        mask=window_masks[j], 
                        pose=poses[j],
                        scale=scale_diff
                    )
                
                self.prev_overlap_raw_pts = pts_list[-self.overlap:]

        print("[Streaming Engine] Sequence processing complete.")
        
        # Extract the final point cloud from the TSDF grid exactly once at the end
        final_pcd = self.tsdf.extract_point_cloud(surface_threshold=0.15)
        
        return final_pcd